name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore src
      run: cd ./src/tool && dotnet restore
    - name: Restore test
      run: cd ./tests/tool && dotnet restore
    - name: Test
      run: cd ./tests/tool && dotnet test --no-restore --verbosity normal
    - name: Pack
      run: cd ./src/tool && dotnet pack --configuration Release
    - name: Publish
      run: cd ./src/tool/nupkg && dotnet nuget push ./*.nupkg --skip-duplicate --no-symbols --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --symbol-api-key ${{secrets.NUGET_API_KEY}}
     
    
